# 设置文件版本
version: '2.4'

services:

  # MongoDB 容器
  mongo:
    container_name: mongo
    build:
      context: ./mongo
      dockerfile: Dockerfile-mongo
    ports:
      - 27017:27017
    networks:
      - matdb
    restart: on-failure

  # SpringBoot 容器
  app:
    container_name: app
    build:
      context: ./
      dockerfile: Dockerfile-app
    ports:
      - 8080:8080
    depends_on:
      - mongo
    networks:
      - matdb
    restart: on-failure

  # Nginx 容器
  nginx:
    container_name: nginx
    build:
      context: ./nginx
      dockerfile: Dockerfile-nginx
    ports:
      - 8083:80
    depends_on:
      - app
    networks:
      - matdb
    restart: on-failure

networks:
  # 设置 MatDB 桥式网络
  matdb:
    name: matdb
    driver: bridge