spring:
  data:
    mongodb:
      host: mongo # 此时为 Docker-Compose 与手动创建容器的配置；如果只需要本地运行 APP.java 测试，或者运行项目 jar 包，可以设置为 localhost
      port: 27017
      authentication-database: admin
      database: admin
      username: root
      password: root