spring:
  resources:
    static-locations: classpath:/static/
  data:
    mongodb:
      host: localhost
      port: 27017
      authentication-database: admin
      database: admin
      username: root
      password: root
