# 指定基础镜像
FROM nginx:1.25.3

# 将本地的静态文件复制到容器中的指定路径
COPY ./html /usr/share/nginx/html

# 将自定义的配置文件复制到容器中
COPY ./nginx.conf /etc/nginx/nginx.conf

# 暴露容器的端口
EXPOSE 80

# 配置数据卷挂载点
VOLUME /usr/share/nginx/html
VOLUME /etc/nginx

# 容器启动时执行的命令
CMD ["nginx", "-g", "daemon off;"]

# 健康检查
HEALTHCHECK --interval=86400s --timeout=10s \
  CMD curl -f http://localhost || exit 1
