# 设置基础镜像
FROM mongo:6.0.8

# 将数据库初始化脚本复制到容器中
COPY init-mongo.js /docker-entrypoint-initdb.d/

# 设置环境变量，相当于设置 root 管理员
ENV MONGO_INITDB_ROOT_USERNAME=root
ENV MONGO_INITDB_ROOT_PASSWORD=root

# 暴露容器的端口
EXPOSE 27017

# 健康检查
HEALTHCHECK --interval=86400s --timeout=10s \
  CMD mongosh --eval "db.adminCommand('ping');" || exit 1